spring.application.name=backend

# إعدادات الاتصال بقاعدة البيانات
spring.datasource.url=jdbc:postgresql://localhost:5432/micro_marketing_db
spring.datasource.username=postgres
# ضع كلمة المرور التي اخترتها أثناء التثبيت هنا
spring.datasource.password=Hda9900

# إعدادات Hibernate (JPA) لإنشاء الجداول تلقائياً
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true